# Generated by Django 3.2.25 on 2025-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('risk', models.FloatField()),
                ('features', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField()),
                ('source', models.CharField(choices=[('gemini', 'Gemini'), ('rule_based', 'Rule based')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
